# Generated by Django 5.1.1 on 2024-10-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Логин')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Игра')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('size', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Размер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('age_limited', models.BooleanField(default=False, verbose_name='Ограничение')),
                ('buyer', models.ManyToManyField(to='task1.buyer')),
            ],
        ),
    ]
