# Generated by Django 5.1.1 on 2024-10-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=110.0, max_digits=10, verbose_name='Баланс'),
        ),
    ]
